version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: cloudms-postgres
    environment:
      POSTGRES_DB: cloudmsdb
      POSTGRES_USER: cloudmsuser
      POSTGRES_PASSWORD: cloudmspassword
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: cloudms-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: cloudms-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-network

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: cloudms-product-service
    depends_on:
      - postgres
      - kafka
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloudmsdb
      SPRING_DATASOURCE_USERNAME: cloudmsuser
      SPRING_DATASOURCE_PASSWORD: cloudmspassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SQS_ORDER_CREATED_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/582500932042/cloudms-dev-order-created-queue
    networks:
      - microservices-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: cloudms-order-service
    depends_on:
      - postgres
      - kafka
      - product-service
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloudmsdb
      SPRING_DATASOURCE_USERNAME: cloudmsuser
      SPRING_DATASOURCE_PASSWORD: cloudmspassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVICES_PRODUCT_URL: http://product-service:8082
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SQS_ORDER_CREATED_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/582500932042/cloudms-dev-order-created-queue
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-data: